name: HarperDB Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-harperdb:
    runs-on: ubuntu-latest
    env:
      HDB_ADMIN_PASSWORD: ${{ secrets.HDB_ADMIN_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Start HarperDB
        run: |
          docker compose up -d
          sleep 15

      - name: Show logs
        run: docker logs $(docker ps -aq --filter "ancestor=harperdb/harperdb")

      - name: Call HarperDB API
        run: |
          curl -X POST http://localhost:9925 -H "Content-Type: application/json" \
          -d '{"operation":"describe_all", "username":"HDB_ADMIN", "password":"${HDB_ADMIN_PASSWORD}"}'
