jobs:
  test-harperdb:
    runs-on: ubuntu-latest
    env:
      HDB_ADMIN_PASSWORD: ${{ secrets.HDB_ADMIN_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Start HarperDB
        run: |
          docker compose up -d
          sleep 10
          docker ps

      - name: Check logs
        run: docker logs $(docker ps -q --filter "ancestor=harperdb/harperdb")
